USE `evento`;

--
-- All countries with a 2-digit code from ISO 3166-1 alpha-2
--
INSERT INTO `country` (`name`, `code`) VALUES
    ('Afghanistan', 'AF'),
    ('Åland Islands', 'AX'),
    ('Albania', 'AL'),
    ('Algeria', 'DZ'),
    ('American Samoa', 'AS'),
    ('Andorra', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctica', 'AQ'),
    ('Antigua and Barbuda', 'AG'),
    ('Argentina', 'AR'),
    ('Armenia', 'AM'),
    ('Aruba', 'AW'),
    ('Australia', 'AU'),
    ('Austria', 'AT'),
    ('Azerbaijan', 'AZ'),
    ('Bahamas', 'BS'),
    ('Bahrain', 'BH'),
    ('Bangladesh', 'BD'),
    ('Barbados', 'BB'),
    ('Belarus', 'BY'),
    ('Belgium', 'BE'),
    ('Belize', 'BZ'),
    ('Benin', 'BJ'),
    ('Bermuda', 'BM'),
    ('Bhutan', 'BT'),
    ('Bolivia', 'BO'),
    ('Bonaire, Sint Eustatius and Saba', 'BQ'),
    ('Bosnia and Herzegovina', 'BA'),
    ('Botswana', 'BW'),
    ('Bouvet Island', 'BV'),
    ('Brazil', 'BR'),
    ('British Indian Ocean Territory', 'IO'),
    ('Brunei Darussalam', 'BN'),
    ('Bulgaria', 'BG'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cabo Verde', 'CV'),
    ('Cambodia', 'KH'),
    ('Cameroon', 'CM'),
    ('Canada', 'CA'),
    ('Cayman Islands', 'KY'),
    ('Central African Republic', 'CF'),
    ('Chad', 'TD'),
    ('Chile', 'CL'),
    ('China', 'CN'),
    ('Christmas Island', 'CX'),
    ('Cocos', 'CC'),
    ('Colombia', 'CO'),
    ('Comoros', 'KM'),
    ('Congo', 'CD'),
    ('Congo', 'CG'),
    ('Cook Islands', 'CK'),
    ('Costa Rica', 'CR'),
    ('Côte d\'Ivoire', 'CI'),
    ('Croatia', 'HR'),
    ('Cuba', 'CU'),
    ('Curaçao', 'CW'),
    ('Cyprus', 'CY'),
    ('Czechia', 'CZ'),
    ('Denmark', 'DK'),
    ('Djibouti', 'DJ'),
    ('Dominica', 'DM'),
    ('Dominican Republic', 'DO'),
    ('Ecuador', 'EC'),
    ('Egypt', 'EG'),
    ('El Salvador', 'SV'),
    ('Equatorial Guinea', 'GQ'),
    ('Eritrea', 'ER'),
    ('Estonia', 'EE'),
    ('Ethiopia', 'ET'),
    ('Falkland Islands [Malvinas]', 'FK'),
    ('Faroe Islands', 'FO'),
    ('Fiji', 'FJ'),
    ('Finland', 'FI'),
    ('France', 'FR'),
    ('French Guiana', 'GF'),
    ('French Polynesia', 'PF'),
    ('French Southern Territories', 'TF'),
    ('Gabon', 'GA'),
    ('Gambia', 'GM'),
    ('Georgia', 'GE'),
    ('Germany', 'DE'),
    ('Ghana', 'GH'),
    ('Gibraltar', 'GI'),
    ('Greece', 'GR'),
    ('Greenland', 'GL'),
    ('Grenada', 'GD'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernsey', 'GG'),
    ('Guinea', 'GN'),
    ('Guinea-Bissau', 'GW'),
    ('Guyana', 'GY'),
    ('Haiti', 'HT'),
    ('Heard Island and McDonald Islands', 'HM'),
    ('Holy See', 'VA'),
    ('Honduras', 'HN'),
    ('Hong Kong', 'HK'),
    ('Hungary', 'HU'),
    ('Iceland', 'IS'),
    ('India', 'IN'),
    ('Indonesia', 'ID'),
    ('Iran', 'IR'),
    ('Iraq', 'IQ'),
    ('Ireland', 'IE'),
    ('Isle of Man', 'IM'),
    ('Israel', 'IL'),
    ('Italy', 'IT'),
    ('Jamaica', 'JM'),
    ('Japan', 'JP'),
    ('Jersey', 'JE'),
    ('Jordan', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kenya', 'KE'),
    ('Kiribati', 'KI'),
    ('Korea', 'KP'),
    ('Korea', 'KR'),
    ('Kuwait', 'KW'),
    ('Kyrgyzstan', 'KG'),
    ('Lao People\'s Democratic Republic', 'LA'),
    ('Latvia', 'LV'),
    ('Lebanon', 'LB'),
    ('Lesotho', 'LS'),
    ('Liberia', 'LR'),
    ('Libya', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Lithuania', 'LT'),
    ('Luxembourg', 'LU'),
    ('Macao', 'MO'),
    ('Macedonia', 'MK'),
    ('Madagascar', 'MG'),
    ('Malawi', 'MW'),
    ('Malaysia', 'MY'),
    ('Maldives', 'MV'),
    ('Mali', 'ML'),
    ('Malta', 'MT'),
    ('Marshall Islands', 'MH'),
    ('Martinique', 'MQ'),
    ('Mauritania', 'MR'),
    ('Mauritius', 'MU'),
    ('Mayotte', 'YT'),
    ('Mexico', 'MX'),
    ('Micronesia', 'FM'),
    ('Moldova', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolia', 'MN'),
    ('Montenegro', 'ME'),
    ('Montserrat', 'MS'),
    ('Morocco', 'MA'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Namibia', 'NA'),
    ('Nauru', 'NR'),
    ('Nepal', 'NP'),
    ('Netherlands', 'NL'),
    ('New Caledonia', 'NC'),
    ('New Zealand', 'NZ'),
    ('Nicaragua', 'NI'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Niue', 'NU'),
    ('Norfolk Island', 'NF'),
    ('Northern Mariana Islands', 'MP'),
    ('Norway', 'NO'),
    ('Oman', 'OM'),
    ('Pakistan', 'PK'),
    ('Palau', 'PW'),
    ('Palestine, State of', 'PS'),
    ('Panama', 'PA'),
    ('Papua New Guinea', 'PG'),
    ('Paraguay', 'PY'),
    ('Peru', 'PE'),
    ('Philippines', 'PH'),
    ('Pitcairn', 'PN'),
    ('Poland', 'PL'),
    ('Portugal', 'PT'),
    ('Puerto Rico', 'PR'),
    ('Qatar', 'QA'),
    ('Réunion', 'RE'),
    ('Romania', 'RO'),
    ('Russian Federation', 'RU'),
    ('Rwanda', 'RW'),
    ('Saint Barthélemy', 'BL'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
    ('Saint Kitts and Nevis', 'KN'),
    ('Saint Lucia', 'LC'),
    ('Saint Martin', 'MF'),
    ('Saint Pierre and Miquelon', 'PM'),
    ('Saint Vincent and the Grenadines', 'VC'),
    ('Samoa', 'WS'),
    ('San Marino', 'SM'),
    ('Sao Tome and Principe', 'ST'),
    ('Saudi Arabia', 'SA'),
    ('Senegal', 'SN'),
    ('Serbia', 'RS'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Singapore', 'SG'),
    ('Sint Maarten', 'SX'),
    ('Slovakia', 'SK'),
    ('Slovenia', 'SI'),
    ('Solomon Islands', 'SB'),
    ('Somalia', 'SO'),
    ('South Africa', 'ZA'),
    ('South Georgia and the South Sandwich Islands', 'GS'),
    ('South Sudan', 'SS'),
    ('Spain', 'ES'),
    ('Sri Lanka', 'LK'),
    ('Sudan', 'SD'),
    ('Suriname', 'SR'),
    ('Svalbard and Jan Mayen', 'SJ'),
    ('Swaziland', 'SZ'),
    ('Sweden', 'SE'),
    ('Switzerland', 'CH'),
    ('Syrian Arab Republic', 'SY'),
    ('Taiwan', 'TW'),
    ('Tajikistan', 'TJ'),
    ('Tanzania', 'TZ'),
    ('Thailand', 'TH'),
    ('Timor-Leste', 'TL'),
    ('Togo', 'TG'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinidad and Tobago', 'TT'),
    ('Tunisia', 'TN'),
    ('Turkey', 'TR'),
    ('Turkmenistan', 'TM'),
    ('Turks and Caicos Islands', 'TC'),
    ('Tuvalu', 'TV'),
    ('Uganda', 'UG'),
    ('Ukraine', 'UA'),
    ('United Arab Emirates', 'AE'),
    ('United Kingdom of Great Britain and Northern Ireland', 'GB'),
    ('United States Minor Outlying Islands', 'UM'),
    ('United States of America', 'US'),
    ('Uruguay', 'UY'),
    ('Uzbekistan', 'UZ'),
    ('Vanuatu', 'VU'),
    ('Venezuela', 'VE'),
    ('Viet Nam', 'VN'),
    ('Virgin Islands', 'VG'),
    ('Virgin Islands', 'VI'),
    ('Wallis and Futuna', 'WF'),
    ('Western Sahara*', 'EH'),
    ('Yemen', 'YE'),
    ('Zambia', 'ZM'),
    ('Zimbabwe', 'ZW');

SET @denmark_id := (SELECT `id` FROM `country` WHERE `code` = 'DK'); 

INSERT INTO `city` (`name`, `country_id`) VALUES
    ('Høje Taastrup', @denmark_id),
    ('København C', @denmark_id),
    ('København K', @denmark_id),
    ('København V', @denmark_id),
    ('Frederiksberg C', @denmark_id),
    ('Frederiksberg', @denmark_id),
    ('København Ø', @denmark_id),
    ('Nordhavn', @denmark_id),
    ('København N', @denmark_id),
    ('København S', @denmark_id),
    ('København NV', @denmark_id),
    ('Grønland', @denmark_id),
    ('København SV', @denmark_id),
    ('Valby', @denmark_id),
    ('Glostrup', @denmark_id),
    ('Brøndby', @denmark_id),
    ('Rødovre', @denmark_id),
    ('Albertslund', @denmark_id),
    ('Vallensbæk', @denmark_id),
    ('Taastrup', @denmark_id),
    ('Ishøj', @denmark_id),
    ('Hedehusene', @denmark_id),
    ('Hvidovre', @denmark_id),
    ('Brøndby Strand', @denmark_id),
    ('Vallensbæk Strand', @denmark_id),
    ('Greve', @denmark_id),
    ('Solrød Strand', @denmark_id),
    ('Karlslunde', @denmark_id),
    ('Brønshøj', @denmark_id),
    ('Vanløse', @denmark_id),
    ('Herlev', @denmark_id),
    ('Skovlunde', @denmark_id),
    ('Ballerup', @denmark_id),
    ('Måløv', @denmark_id),
    ('Smørum', @denmark_id),
    ('Kastrup', @denmark_id),
    ('Dragør', @denmark_id),
    ('Kongens Lyngby', @denmark_id),
    ('Gentofte', @denmark_id),
    ('Virum', @denmark_id),
    ('Holte', @denmark_id),
    ('Nærum', @denmark_id),
    ('Søborg', @denmark_id),
    ('Dyssegård', @denmark_id),
    ('Bagsværd', @denmark_id),
    ('Hellerup', @denmark_id),
    ('Charlottenlund', @denmark_id),
    ('Klampenborg', @denmark_id),
    ('Skodsborg', @denmark_id),
    ('Vedbæk', @denmark_id),
    ('Rungsted Kyst', @denmark_id),
    ('Hørsholm', @denmark_id),
    ('Kokkedal', @denmark_id),
    ('Nivå', @denmark_id),
    ('Helsingør', @denmark_id),
    ('Humlebæk', @denmark_id),
    ('Espergærde', @denmark_id),
    ('Snekkersten', @denmark_id),
    ('Tikøb', @denmark_id),
    ('Hornbæk', @denmark_id),
    ('Dronningmølle', @denmark_id),
    ('Ålsgårde', @denmark_id),
    ('Hellebæk', @denmark_id),
    ('Helsinge', @denmark_id),
    ('Vejby', @denmark_id),
    ('Tisvildeleje', @denmark_id),
    ('Græsted', @denmark_id),
    ('Gilleleje', @denmark_id),
    ('Frederiksværk', @denmark_id),
    ('Ølsted', @denmark_id),
    ('Skævinge', @denmark_id),
    ('Gørløse', @denmark_id),
    ('Liseleje', @denmark_id),
    ('Melby', @denmark_id),
    ('Hundested', @denmark_id),
    ('Hillerød', @denmark_id),
    ('Allerød', @denmark_id),
    ('Birkerød', @denmark_id),
    ('Fredensborg', @denmark_id),
    ('Kvistgård', @denmark_id),
    ('Værløse', @denmark_id),
    ('Farum', @denmark_id),
    ('Lynge', @denmark_id),
    ('Slangerup', @denmark_id),
    ('Frederikssund', @denmark_id),
    ('Jægerspris', @denmark_id),
    ('Ølstykke', @denmark_id),
    ('Stenløse', @denmark_id),
    ('Veksø Sjælland', @denmark_id),
    ('Rønne', @denmark_id),
    ('Aakirkeby', @denmark_id),
    ('Nexø', @denmark_id),
    ('Svaneke', @denmark_id),
    ('Østermarie', @denmark_id),
    ('Gudhjem', @denmark_id),
    ('Allinge', @denmark_id),
    ('Klemensker', @denmark_id),
    ('Hasle', @denmark_id),
    ('Roskilde', @denmark_id),
    ('Tune', @denmark_id),
    ('Jyllinge', @denmark_id),
    ('Skibby', @denmark_id),
    ('Kirke Såby', @denmark_id),
    ('Kirke Hyllinge', @denmark_id),
    ('Ringsted', @denmark_id),
    ('Viby Sjælland', @denmark_id),
    ('Borup', @denmark_id),
    ('Herlufmagle', @denmark_id),
    ('Glumsø', @denmark_id),
    ('Fjenneslev', @denmark_id),
    ('Jystrup Midtsj', @denmark_id),
    ('Sorø', @denmark_id),
    ('Munke Bjergby', @denmark_id),
    ('Slagelse', @denmark_id),
    ('Korsør', @denmark_id),
    ('Skælskør', @denmark_id),
    ('Vemmelev', @denmark_id),
    ('Boeslunde', @denmark_id),
    ('Rude', @denmark_id),
    ('Agersø', @denmark_id),
    ('Omø', @denmark_id),
    ('Fuglebjerg', @denmark_id),
    ('Dalmose', @denmark_id),
    ('Sandved', @denmark_id),
    ('Høng', @denmark_id),
    ('Gørlev', @denmark_id),
    ('Ruds Vedby', @denmark_id),
    ('Dianalund', @denmark_id),
    ('Stenlille', @denmark_id),
    ('Nyrup', @denmark_id),
    ('Holbæk', @denmark_id),
    ('Orø', @denmark_id),
    ('Lejre', @denmark_id),
    ('Hvalsø', @denmark_id),
    ('Tølløse', @denmark_id),
    ('Ugerløse', @denmark_id),
    ('Kirke Eskilstrup', @denmark_id),
    ('Store Merløse', @denmark_id),
    ('Vipperød', @denmark_id),
    ('Kalundborg', @denmark_id),
    ('Regstrup', @denmark_id),
    ('Mørkøv', @denmark_id),
    ('Jyderup', @denmark_id),
    ('Snertinge', @denmark_id),
    ('Svebølle', @denmark_id),
    ('Store Fuglede', @denmark_id),
    ('Jerslev Sjælland', @denmark_id),
    ('Nykøbing Sj', @denmark_id),
    ('Svinninge', @denmark_id),
    ('Gislinge', @denmark_id),
    ('Hørve', @denmark_id),
    ('Fårevejle', @denmark_id),
    ('Asnæs', @denmark_id),
    ('Vig', @denmark_id),
    ('Grevinge', @denmark_id),
    ('Nørre Asmindrup', @denmark_id),
    ('Højby', @denmark_id),
    ('Rørvig', @denmark_id),
    ('Sjællands Odde', @denmark_id),
    ('Føllenslev', @denmark_id),
    ('Sejerø', @denmark_id),
    ('Eskebjerg', @denmark_id),
    ('Køge', @denmark_id),
    ('Gadstrup', @denmark_id),
    ('Havdrup', @denmark_id),
    ('Lille Skensved', @denmark_id),
    ('Bjæverskov', @denmark_id),
    ('Faxe', @denmark_id),
    ('Hårlev', @denmark_id),
    ('Karise', @denmark_id),
    ('Faxe Ladeplads', @denmark_id),
    ('Store Heddinge', @denmark_id),
    ('Strøby', @denmark_id),
    ('Klippinge', @denmark_id),
    ('Rødvig Stevns', @denmark_id),
    ('Herfølge', @denmark_id),
    ('Tureby', @denmark_id),
    ('Rønnede', @denmark_id),
    ('Holmegaard', @denmark_id),
    ('Haslev', @denmark_id),
    ('Næstved', @denmark_id),
    ('Præstø', @denmark_id),
    ('Tappernøje', @denmark_id),
    ('Mern', @denmark_id),
    ('Karrebæksminde', @denmark_id),
    ('Lundby', @denmark_id),
    ('Vordingborg', @denmark_id),
    ('Kalvehave', @denmark_id),
    ('Langebæk', @denmark_id),
    ('Stensved', @denmark_id),
    ('Stege', @denmark_id),
    ('Borre', @denmark_id),
    ('Askeby', @denmark_id),
    ('Bogø By', @denmark_id),
    ('Nykøbing F', @denmark_id),
    ('Nørre Alslev', @denmark_id),
    ('Stubbekøbing', @denmark_id),
    ('Guldborg', @denmark_id),
    ('Eskilstrup', @denmark_id),
    ('Horbelev', @denmark_id),
    ('Idestrup', @denmark_id),
    ('Væggerløse', @denmark_id),
    ('Gedser', @denmark_id),
    ('Nysted', @denmark_id),
    ('Toreby L', @denmark_id),
    ('Kettinge', @denmark_id),
    ('Øster Ulslev', @denmark_id),
    ('Errindlev', @denmark_id),
    ('Nakskov', @denmark_id),
    ('Harpelunde', @denmark_id),
    ('Horslunde', @denmark_id),
    ('Søllested', @denmark_id),
    ('Maribo', @denmark_id),
    ('Bandholm', @denmark_id),
    ('Askø og Lilleø', @denmark_id),
    ('Torrig L', @denmark_id),
    ('Fejø', @denmark_id),
    ('Femø', @denmark_id),
    ('Nørreballe', @denmark_id),
    ('Stokkemarke', @denmark_id),
    ('Vesterborg', @denmark_id),
    ('Holeby', @denmark_id),
    ('Rødby', @denmark_id),
    ('Dannemare', @denmark_id),
    ('Sakskøbing', @denmark_id),
    ('Odense C', @denmark_id),
    ('Odense V', @denmark_id),
    ('Odense NV', @denmark_id),
    ('Odense SØ', @denmark_id),
    ('Odense M', @denmark_id),
    ('Odense NØ', @denmark_id),
    ('Odense SV', @denmark_id),
    ('Odense S', @denmark_id),
    ('Odense N', @denmark_id),
    ('Marslev', @denmark_id),
    ('Kerteminde', @denmark_id),
    ('Agedrup', @denmark_id),
    ('Munkebo', @denmark_id),
    ('Rynkeby', @denmark_id),
    ('Mesinge', @denmark_id),
    ('Dalby', @denmark_id),
    ('Martofte', @denmark_id),
    ('Bogense', @denmark_id),
    ('Otterup', @denmark_id),
    ('Morud', @denmark_id),
    ('Harndrup', @denmark_id),
    ('Brenderup Fyn', @denmark_id),
    ('Asperup', @denmark_id),
    ('Søndersø', @denmark_id),
    ('Veflinge', @denmark_id),
    ('Skamby', @denmark_id),
    ('Blommenslyst', @denmark_id),
    ('Vissenbjerg', @denmark_id),
    ('Middelfart', @denmark_id),
    ('Ullerslev', @denmark_id),
    ('Langeskov', @denmark_id),
    ('Aarup', @denmark_id),
    ('Nørre Aaby', @denmark_id),
    ('Gelsted', @denmark_id),
    ('Ejby', @denmark_id),
    ('Faaborg', @denmark_id),
    ('Bjørnø', @denmark_id),
    ('Assens', @denmark_id),
    ('Glamsbjerg', @denmark_id),
    ('Ebberup', @denmark_id),
    ('Millinge', @denmark_id),
    ('Broby', @denmark_id),
    ('Haarby', @denmark_id),
    ('Tommerup', @denmark_id),
    ('Svendborg', @denmark_id),
    ('Ringe', @denmark_id),
    ('Vester Skerninge', @denmark_id),
    ('Stenstrup', @denmark_id),
    ('Kværndrup', @denmark_id),
    ('Årslev', @denmark_id),
    ('Nyborg', @denmark_id),
    ('Ørbæk', @denmark_id),
    ('Gislev', @denmark_id),
    ('Ryslinge', @denmark_id),
    ('Ferritslev Fyn', @denmark_id),
    ('Frørup', @denmark_id),
    ('Hesselager', @denmark_id),
    ('Skårup Fyn', @denmark_id),
    ('Vejstrup', @denmark_id),
    ('Oure', @denmark_id),
    ('Gudme', @denmark_id),
    ('Gudbjerg Sydfyn', @denmark_id),
    ('Rudkøbing', @denmark_id),
    ('Humble', @denmark_id),
    ('Bagenkop', @denmark_id),
    ('Strynø', @denmark_id),
    ('Tranekær', @denmark_id),
    ('Marstal', @denmark_id),
    ('Ærøskøbing', @denmark_id),
    ('Søby Ærø', @denmark_id),
    ('Kolding', @denmark_id),
    ('Egtved', @denmark_id),
    ('Almind', @denmark_id),
    ('Viuf', @denmark_id),
    ('Jordrup', @denmark_id),
    ('Christiansfeld', @denmark_id),
    ('Bjert', @denmark_id),
    ('Sønder Stenderup', @denmark_id),
    ('Sjølund', @denmark_id),
    ('Hejls', @denmark_id),
    ('Haderslev', @denmark_id),
    ('Aabenraa', @denmark_id),
    ('Barsø', @denmark_id),
    ('Rødekro', @denmark_id),
    ('Løgumkloster', @denmark_id),
    ('Bredebro', @denmark_id),
    ('Tønder', @denmark_id),
    ('Højer', @denmark_id),
    ('Gråsten', @denmark_id),
    ('Broager', @denmark_id),
    ('Egernsund', @denmark_id),
    ('Padborg', @denmark_id),
    ('Kruså', @denmark_id),
    ('Tinglev', @denmark_id),
    ('Bylderup-Bov', @denmark_id),
    ('Bolderslev', @denmark_id),
    ('Sønderborg', @denmark_id),
    ('Nordborg', @denmark_id),
    ('Augustenborg', @denmark_id),
    ('Sydals', @denmark_id),
    ('Vojens', @denmark_id),
    ('Gram', @denmark_id),
    ('Toftlund', @denmark_id),
    ('Agerskov', @denmark_id),
    ('Branderup J', @denmark_id),
    ('Bevtoft', @denmark_id),
    ('Sommersted', @denmark_id),
    ('Vamdrup', @denmark_id),
    ('Vejen', @denmark_id),
    ('Gesten', @denmark_id),
    ('Bække', @denmark_id),
    ('Vorbasse', @denmark_id),
    ('Rødding', @denmark_id),
    ('Lunderskov', @denmark_id),
    ('Brørup', @denmark_id),
    ('Lintrup', @denmark_id),
    ('Holsted', @denmark_id),
    ('Hovborg', @denmark_id),
    ('Føvling', @denmark_id),
    ('Gørding', @denmark_id),
    ('Esbjerg', @denmark_id),
    ('Esbjerg Ø', @denmark_id),
    ('Esbjerg V', @denmark_id),
    ('Esbjerg N', @denmark_id),
    ('Fanø', @denmark_id),
    ('Tjæreborg', @denmark_id),
    ('Bramming', @denmark_id),
    ('Glejbjerg', @denmark_id),
    ('Agerbæk', @denmark_id),
    ('Ribe', @denmark_id),
    ('Gredstedbro', @denmark_id),
    ('Skærbæk', @denmark_id),
    ('Rømø', @denmark_id),
    ('Varde', @denmark_id),
    ('Årre', @denmark_id),
    ('Ansager', @denmark_id),
    ('Nørre Nebel', @denmark_id),
    ('Oksbøl', @denmark_id),
    ('Janderup Vestj', @denmark_id),
    ('Billum', @denmark_id),
    ('Vejers Strand', @denmark_id),
    ('Henne', @denmark_id),
    ('Outrup', @denmark_id),
    ('Blåvand', @denmark_id),
    ('Tistrup', @denmark_id),
    ('Ølgod', @denmark_id),
    ('Tarm', @denmark_id),
    ('Hemmet', @denmark_id),
    ('Skjern', @denmark_id),
    ('Videbæk', @denmark_id),
    ('Kibæk', @denmark_id),
    ('Lem St', @denmark_id),
    ('Ringkøbing', @denmark_id),
    ('Hvide Sande', @denmark_id),
    ('Spjald', @denmark_id),
    ('Ørnhøj', @denmark_id),
    ('Tim', @denmark_id),
    ('Ulfborg', @denmark_id),
    ('Fredericia', @denmark_id),
    ('Taulov Pakkecenter', @denmark_id),
    ('Børkop', @denmark_id),
    ('Vejle', @denmark_id),
    ('Vejle Øst', @denmark_id),
    ('Juelsminde', @denmark_id),
    ('Stouby', @denmark_id),
    ('Barrit', @denmark_id),
    ('Tørring', @denmark_id),
    ('Uldum', @denmark_id),
    ('Vonge', @denmark_id),
    ('Bredsten', @denmark_id),
    ('Randbøl', @denmark_id),
    ('Vandel', @denmark_id),
    ('Billund', @denmark_id),
    ('Grindsted', @denmark_id),
    ('Hejnsvig', @denmark_id),
    ('Sønder Omme', @denmark_id),
    ('Stakroge', @denmark_id),
    ('Sønder Felding', @denmark_id),
    ('Jelling', @denmark_id),
    ('Gadbjerg', @denmark_id),
    ('Give', @denmark_id),
    ('Brande', @denmark_id),
    ('Ejstrupholm', @denmark_id),
    ('Hampen', @denmark_id),
    ('Herning', @denmark_id),
    ('Ikast', @denmark_id),
    ('Bording', @denmark_id),
    ('Engesvang', @denmark_id),
    ('Sunds', @denmark_id),
    ('Karup J', @denmark_id),
    ('Vildbjerg', @denmark_id),
    ('Aulum', @denmark_id),
    ('Holstebro', @denmark_id),
    ('Haderup', @denmark_id),
    ('Sørvad', @denmark_id),
    ('Hjerm', @denmark_id),
    ('Vemb', @denmark_id),
    ('Struer', @denmark_id),
    ('Lemvig', @denmark_id),
    ('Bøvlingbjerg', @denmark_id),
    ('Bækmarksbro', @denmark_id),
    ('Harboøre', @denmark_id),
    ('Thyborøn', @denmark_id),
    ('Thisted', @denmark_id),
    ('Hanstholm', @denmark_id),
    ('Frøstrup', @denmark_id),
    ('Vesløs', @denmark_id),
    ('Snedsted', @denmark_id),
    ('Bedsted Thy', @denmark_id),
    ('Hurup Thy', @denmark_id),
    ('Vestervig', @denmark_id),
    ('Thyholm', @denmark_id),
    ('Skive', @denmark_id),
    ('Vinderup', @denmark_id),
    ('Højslev', @denmark_id),
    ('Stoholm Jyll', @denmark_id),
    ('Spøttrup', @denmark_id),
    ('Roslev', @denmark_id),
    ('Fur', @denmark_id),
    ('Nykøbing M', @denmark_id),
    ('Erslev', @denmark_id),
    ('Karby', @denmark_id),
    ('Redsted M', @denmark_id),
    ('Vils', @denmark_id),
    ('Øster Assels', @denmark_id),
    ('Fakturaservice', @denmark_id),
    ('Fakturascanning', @denmark_id),
    ('Statsservice', @denmark_id),
    ('Kommunepost', @denmark_id),
    ('Aarhus C', @denmark_id),
    ('Aarhus N', @denmark_id),
    ('Aarhus V', @denmark_id),
    ('Brabrand', @denmark_id),
    ('Risskov Ø', @denmark_id),
    ('Åbyhøj', @denmark_id),
    ('Risskov', @denmark_id),
    ('Egå', @denmark_id),
    ('Viby J', @denmark_id),
    ('Højbjerg', @denmark_id),
    ('Odder', @denmark_id),
    ('Samsø', @denmark_id),
    ('Tranbjerg J', @denmark_id),
    ('Mårslet', @denmark_id),
    ('Beder', @denmark_id),
    ('Malling', @denmark_id),
    ('Hundslund', @denmark_id),
    ('Solbjerg', @denmark_id),
    ('Hasselager', @denmark_id),
    ('Hørning', @denmark_id),
    ('Hadsten', @denmark_id),
    ('Trige', @denmark_id),
    ('Tilst', @denmark_id),
    ('Hinnerup', @denmark_id),
    ('Ebeltoft', @denmark_id),
    ('Rønde', @denmark_id),
    ('Knebel', @denmark_id),
    ('Balle', @denmark_id),
    ('Hammel', @denmark_id),
    ('Harlev J', @denmark_id),
    ('Galten', @denmark_id),
    ('Sabro', @denmark_id),
    ('Sporup', @denmark_id),
    ('Grenaa', @denmark_id),
    ('Lystrup', @denmark_id),
    ('Hjortshøj', @denmark_id),
    ('Skødstrup', @denmark_id),
    ('Hornslet', @denmark_id),
    ('Mørke', @denmark_id),
    ('Ryomgård', @denmark_id),
    ('Kolind', @denmark_id),
    ('Trustrup', @denmark_id),
    ('Nimtofte', @denmark_id),
    ('Glesborg', @denmark_id),
    ('Ørum Djurs', @denmark_id),
    ('Anholt', @denmark_id),
    ('Silkeborg', @denmark_id),
    ('Kjellerup', @denmark_id),
    ('Lemming', @denmark_id),
    ('Sorring', @denmark_id),
    ('Ans By', @denmark_id),
    ('Them', @denmark_id),
    ('Bryrup', @denmark_id),
    ('Skanderborg', @denmark_id),
    ('Låsby', @denmark_id),
    ('Ry', @denmark_id),
    ('Horsens', @denmark_id),
    ('Daugård', @denmark_id),
    ('Hedensted', @denmark_id),
    ('Løsning', @denmark_id),
    ('Hovedgård', @denmark_id),
    ('Brædstrup', @denmark_id),
    ('Gedved', @denmark_id),
    ('Østbirk', @denmark_id),
    ('Flemming', @denmark_id),
    ('Rask Mølle', @denmark_id),
    ('Klovborg', @denmark_id),
    ('Nørre Snede', @denmark_id),
    ('Stenderup', @denmark_id),
    ('Hornsyld', @denmark_id),
    ('Viborg', @denmark_id),
    ('Tjele', @denmark_id),
    ('Løgstrup', @denmark_id),
    ('Skals', @denmark_id),
    ('Rødkærsbro', @denmark_id),
    ('Bjerringbro', @denmark_id),
    ('Ulstrup', @denmark_id),
    ('Langå', @denmark_id),
    ('Thorsø', @denmark_id),
    ('Fårvang', @denmark_id),
    ('Gjern', @denmark_id),
    ('Randers C', @denmark_id),
    ('Randers NV', @denmark_id),
    ('Randers NØ', @denmark_id),
    ('Randers SV', @denmark_id),
    ('Ørsted', @denmark_id),
    ('Randers SØ', @denmark_id),
    ('Allingåbro', @denmark_id),
    ('Auning', @denmark_id),
    ('Havndal', @denmark_id),
    ('Spentrup', @denmark_id),
    ('Gjerlev J', @denmark_id),
    ('Fårup', @denmark_id),
    ('Aalborg', @denmark_id),
    ('Aalborg SV', @denmark_id),
    ('Aalborg SØ', @denmark_id),
    ('Aalborg Øst', @denmark_id),
    ('Svenstrup J', @denmark_id),
    ('Nibe', @denmark_id),
    ('Gistrup', @denmark_id),
    ('Klarup', @denmark_id),
    ('Storvorde', @denmark_id),
    ('Kongerslev', @denmark_id),
    ('Sæby', @denmark_id),
    ('Vodskov', @denmark_id),
    ('Hjallerup', @denmark_id),
    ('Dronninglund', @denmark_id),
    ('Asaa', @denmark_id),
    ('Dybvad', @denmark_id),
    ('Gandrup', @denmark_id),
    ('Hals', @denmark_id),
    ('Vestbjerg', @denmark_id),
    ('Sulsted', @denmark_id),
    ('Tylstrup', @denmark_id),
    ('Nørresundby', @denmark_id),
    ('Vadum', @denmark_id),
    ('Aabybro', @denmark_id),
    ('Brovst', @denmark_id),
    ('Løkken', @denmark_id),
    ('Pandrup', @denmark_id),
    ('Blokhus', @denmark_id),
    ('Saltum', @denmark_id),
    ('Hobro', @denmark_id),
    ('Arden', @denmark_id),
    ('Skørping', @denmark_id),
    ('Støvring', @denmark_id),
    ('Suldrup', @denmark_id),
    ('Mariager', @denmark_id),
    ('Hadsund', @denmark_id),
    ('Bælum', @denmark_id),
    ('Terndrup', @denmark_id),
    ('Aars', @denmark_id),
    ('Nørager', @denmark_id),
    ('Aalestrup', @denmark_id),
    ('Gedsted', @denmark_id),
    ('Møldrup', @denmark_id),
    ('Farsø', @denmark_id),
    ('Løgstør', @denmark_id),
    ('Ranum', @denmark_id),
    ('Fjerritslev', @denmark_id),
    ('Brønderslev', @denmark_id),
    ('Jerslev J', @denmark_id),
    ('Østervrå', @denmark_id),
    ('Vrå', @denmark_id),
    ('Hjørring', @denmark_id),
    ('Tårs', @denmark_id),
    ('Hirtshals', @denmark_id),
    ('Sindal', @denmark_id),
    ('Bindslev', @denmark_id),
    ('Frederikshavn', @denmark_id),
    ('Læsø', @denmark_id),
    ('Strandby', @denmark_id),
    ('Jerup', @denmark_id),
    ('Ålbæk', @denmark_id),
    ('Skagen', @denmark_id),
    ('Borgerservice', @denmark_id),
    ('Santa Claus/Julemanden', @denmark_id),
    ('Nuuk', @denmark_id),
    ('Nuussuaq', @denmark_id),
    ('Kangerlussuaq', @denmark_id),
    ('Sisimiut', @denmark_id),
    ('Maniitsoq', @denmark_id),
    ('Tasiilaq', @denmark_id),
    ('Kulusuk', @denmark_id),
    ('Alluitsup Paa', @denmark_id),
    ('Qaqortoq', @denmark_id),
    ('Narsaq', @denmark_id),
    ('Nanortalik', @denmark_id),
    ('Narsarsuaq', @denmark_id),
    ('Ikerasassuaq', @denmark_id),
    ('Kangilinnguit', @denmark_id),
    ('Arsuk', @denmark_id),
    ('Paamiut', @denmark_id),
    ('Aasiaat', @denmark_id),
    ('Qasigiannguit', @denmark_id),
    ('Ilulissat', @denmark_id),
    ('Qeqertarsuaq', @denmark_id),
    ('Kangaatsiaq', @denmark_id),
    ('Uummannaq', @denmark_id),
    ('Upernavik', @denmark_id),
    ('Qaarsut', @denmark_id),
    ('Pituffik', @denmark_id),
    ('Qaanaaq', @denmark_id),
    ('Station Nord', @denmark_id),
    ('Ittoqqortoormiit', @denmark_id),
    ('Mestersvig', @denmark_id),
    ('Danmarkshavn', @denmark_id),
    ('Constable Pynt', @denmark_id),
    ('Slædepatrulje Sirius', @denmark_id),
    ('Tórshavn', @denmark_id),
    ('Argir', @denmark_id),
    ('Kirkjubøur', @denmark_id),
    ('Velbastadur', @denmark_id),
    ('Sydradalur, Streymoy', @denmark_id),
    ('Nordradalur', @denmark_id),
    ('Kaldbak', @denmark_id),
    ('Kaldbaksbotnur', @denmark_id),
    ('Sund', @denmark_id),
    ('Hvitanes', @denmark_id),
    ('Hoyvík', @denmark_id),
    ('Sandur', @denmark_id),
    ('Skálavík', @denmark_id),
    ('Húsavík', @denmark_id),
    ('Dalur', @denmark_id),
    ('Skarvanes', @denmark_id),
    ('Skopun', @denmark_id),
    ('Skúvoy', @denmark_id),
    ('Nólsoy', @denmark_id),
    ('Hestur', @denmark_id),
    ('Koltur', @denmark_id),
    ('Stóra Dimun', @denmark_id),
    ('Stykkid', @denmark_id),
    ('Leynar', @denmark_id),
    ('Skællingur', @denmark_id),
    ('Kvívík', @denmark_id),
    ('Vestmanna', @denmark_id),
    ('Válur', @denmark_id),
    ('Sandavágur', @denmark_id),
    ('Midvágur', @denmark_id),
    ('Sørvágur', @denmark_id),
    ('Vatnsoyrar', @denmark_id),
    ('Bøur', @denmark_id),
    ('Gásadalur', @denmark_id),
    ('Mykines', @denmark_id),
    ('Oyrarbakki', @denmark_id),
    ('Kollafjørdur', @denmark_id),
    ('Oyrareingir', @denmark_id),
    ('Signabøur', @denmark_id),
    ('Hósvík', @denmark_id),
    ('Hvalvík', @denmark_id),
    ('Streymnes', @denmark_id),
    ('Saksun', @denmark_id),
    ('Nesvík', @denmark_id),
    ('Langasandur', @denmark_id),
    ('Haldarsvík', @denmark_id),
    ('Tjørnuvík', @denmark_id),
    ('Oyri', @denmark_id),
    ('Nordskáli', @denmark_id),
    ('Svináir', @denmark_id),
    ('Ljósá', @denmark_id),
    ('Eidi', @denmark_id),
    ('Funningur', @denmark_id),
    ('Gjógv', @denmark_id),
    ('Funningsfjørdur', @denmark_id),
    ('Elduvík', @denmark_id),
    ('Skáli', @denmark_id),
    ('Skálafjørdur', @denmark_id),
    ('Strendur', @denmark_id),
    ('Innan Glyvur', @denmark_id),
    ('Kolbanargjógv', @denmark_id),
    ('Morskranes', @denmark_id),
    ('Selatrad', @denmark_id),
    ('Gøta', @denmark_id),
    ('Gøtugjógv', @denmark_id),
    ('Nordragøta', @denmark_id),
    ('Sydrugøta', @denmark_id),
    ('Leirvík', @denmark_id),
    ('Fuglafjørdur', @denmark_id),
    ('Saltangará', @denmark_id),
    ('Runavík', @denmark_id),
    ('Glyvrar', @denmark_id),
    ('Lambareidi', @denmark_id),
    ('Lambi', @denmark_id),
    ('Rituvík', @denmark_id),
    ('Æduvík', @denmark_id),
    ('Toftir', @denmark_id),
    ('Nes, Eysturoy', @denmark_id),
    ('Saltnes', @denmark_id),
    ('Søldarfjørdur', @denmark_id),
    ('Skipanes', @denmark_id),
    ('Gøtueidi', @denmark_id),
    ('Oyndarfjørdur', @denmark_id),
    ('Hellur', @denmark_id),
    ('Klaksvík', @denmark_id),
    ('Nordoyri', @denmark_id),
    ('Ánir', @denmark_id),
    ('Árnafjørdur', @denmark_id),
    ('Norddepil', @denmark_id),
    ('Depil', @denmark_id),
    ('Nordtoftir', @denmark_id),
    ('Múli', @denmark_id),
    ('Hvannasund', @denmark_id),
    ('Vidareidi', @denmark_id),
    ('Svinoy', @denmark_id),
    ('Kirkja', @denmark_id),
    ('Hattarvík', @denmark_id),
    ('Kunoy', @denmark_id),
    ('Haraldssund', @denmark_id),
    ('Sydradalur, Kalsoy', @denmark_id),
    ('Húsar', @denmark_id),
    ('Mikladalur', @denmark_id),
    ('Trøllanes', @denmark_id),
    ('Tvøroyri', @denmark_id),
    ('Frodba', @denmark_id),
    ('Trongisvágur', @denmark_id),
    ('Øravík', @denmark_id),
    ('Hvalba', @denmark_id),
    ('Sandvík', @denmark_id),
    ('Fámjin', @denmark_id),
    ('Vágur', @denmark_id),
    ('Nes, Vágur', @denmark_id),
    ('Lopra', @denmark_id),
    ('Akrar', @denmark_id),
    ('Vikarbyrgi', @denmark_id),
    ('Porkeri', @denmark_id),
    ('Hov', @denmark_id),
    ('Sumba', @denmark_id);